name: Run ETL

on:
  workflow_dispatch:
    inputs:
      organization_id:
        description: 'Organization ID'
        required: true
        type: string

jobs:
  run-etl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r etl/requirements.txt

      - name: Run ETL
        run: |
          python etl/transform_pipeline/transform_and_insert.py --organization-id "${{ github.event.inputs.organization_id }}"
        env:
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }} 