# render.yaml
services:
  - type: web
    name: nanonets-webhook
    env: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python start.py
    healthCheckPath: /healthz
    envVars:
      - key: DATABASE_URL
        fromDotEnv: true
      - key: NANONETS_MODEL_ID
        fromDotEnv: true
      - key: DEFAULT_ORG_ID
        fromDotEnv: true
