name: ETL

on:
  workflow_dispatch:
    inputs:
      organization_id:
        description: Organization ID to process
        required: true
        type: string

jobs:
  run-etl:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    env:
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('services/api/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        working-directory: services/api
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run ETL (transform_and_insert)
        working-directory: services/api/etl/transform_pipeline
        run: |
          python transform_and_insert.py --organization-id "${{ inputs.organization_id }}"

      - name: Summary
        run: |
          echo "ETL completed for organization_id=${{ inputs.organization_id }}" >> $GITHUB_STEP_SUMMARY


